name: ScoutingEyes
version: ${project.version}
main: io.github.jmh07.scoutingeyes.ScoutingEyes
api-version: 1.15
authors: [Fahnatek]
description: Adds a new item labled "Eye of ...". This allows the user to search for players around you.

commands:
  scouteyes:
    usage: /scouteyes [basic|omega] [amount] - Gives player a [basic or omega] scouting eyes and an [amount] of scoutingeyes.
    permission: minecraft-scouteyes.command.use
    description: Adds a Eye of the Lord to the players inventory.

permissions:
  minecraft-scouteyes.command.use:
    description: Allows a player to use the command to spawn Scouting Eyes
    default: op

  minecraft-scouteyes.hidden:
    description: Hides certain players from being found by the eye. Best to give the Scouts this permission.
    default: op