name: ScoutingDevice
version: ${project.version}
main: io.github.jmh07.scoutingeyes.ScoutingEyes
api-version: 1.15
authors: [Fahnatek]
description: Adds a new item labled "Scouting Device". This allows the user to search for players around you.

commands:
  scouteyes:
    usage: /scouteyes [basic|omega] [amount] - Gives player a [basic or omega] scouting eyes and an [amount] of scoutingeyes.
    permission: minecraft-scouteyes.use
    description: Adds a Eye of the Lord to the players inventory.